[tool.poetry]
name = "mppsolar"
version = "0.16.16"
description = "Package to communicate with Solar inverters and BMSs"
authors = ["John Blance"]
readme = "README.md"
packages = [
    {include = "mppsolar"},
    {include = "powermon"},
    {include = "api"},
    {include = "powermon_api"},
]

[tool.poetry.dependencies]
python = ">=3.10,<4.00"
pyserial = ">3"
pydantic = ">=1.8.0"

# Extra dependencies
fastapi = { version = ">=0.68.0", extras = ["api"] }
fastapi-mqtt = { version = ">=1.1", extras = ["api"] }
sqlalchemy = { version = "^2.0.15", extras = ["api"] }
uvicorn = { version = ">=0.15.0", extras = ["api"] }
bleak = { version = "^0.20.2", extras = ["ble"] }
bluepy = { version = "^1.3.0", extras = ["ble"] }
paho-mqtt = { version = ">=1.6", extras = ["mqtt"] }
requests = { version = ">=2.31.0", extras = ["push"] }
PyYAML = { version = ">=62.31.0", extras = ["powermon"] }
strenum = { version = "^0.4.1", extras = ["powermon"] }
systemd = { version = ">=0.17.1", extras = ["systemd"] }

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"
flake8 = "^6.0.0"
black = "^23.3.0"
coverage = "^7.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mpp-solar = "mppsolar:main"
mppsolar = "mppsolar:main"
jkbms = "mppsolar:main"
powermon = "powermon:main"
powermon-api = "powermon_api.api:main"

[tool.black]
line-length = 149
